FROM python:3.8-alpine

ARG TOKEN
ARG ACCESS
ARG TRANSMISSION_URL=localhost
ARG TRANSMISSION_LOGIN
ARG TRANSMISSION_PASSWORD
ARG TRANSMISSION_PORT
ARG TIME_SHEDULE_SEC=300
ARG SOCKS5_LOGIN 
ARG SOCKS5_PASSWORD
ARG SOCKS5_ADDRESS

ENV TOKEN=${TOKEN}
ENV ACCESS=${ACCESS}
ENV TRANSMISSION_URL=${TRANSMISSION_URL}
ENV TRANSMISSION_LOGIN=${TRANSMISSION_LOGIN}
ENV TRANSMISSION_PASSWORD=${TRANSMISSION_PASSWORD}
ENV TRANSMISSION_PORT=${TRANSMISSION_PORT}
ENV TIME_SHEDULE_SEC=${TIME_SHEDULE_SEC}
ENV SOCKS5_LOGIN=${SOCKS5_LOGIN}
ENV SOCKS5_PASSWORD=${SOCKS5_PASSWORD}
ENV SOCKS5_ADDRESS=${SOCKS5_ADDRESS}

WORKDIR /transmission_telegram

COPY requirements.txt .
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

COPY . /transmission_telegram/

ENTRYPOINT ["python", "bot.py", "&"]
CMD ["python ", "shedule.py", "&"]

EXPOSE 443